export const SET_INFO_EXAM = 'SET_INFO_EXAM';
export const SET_CURRENT_SECTION = 'SET_CURRENT_SECTION';
export const SELECT_PART = 'SELECT_PART';
export const RESET_PART = 'RESET_PART';
export const UPDATE_STATUS_PART = 'UPDATE_STATUS_PART';
export const UPDATE_STATUS_QUESTION = 'UPDATE_STATUS_QUESTION';
export const RESET_EXAM = 'RESET_EXAM';
export const INCREASE_SCORE_EXAM = 'INCREASE_SCORE_EXAM';
export const SHOW_RESULT = 'SHOW_RESULT';

export const FETCH_EXAM_FEATURE = 'FETCH_EXAM_FEATURE';
export const FETCH_EXAM_FEATURE_SUCCESS = 'FETCH_EXAM_FEATURE_SUCCESS';
export const FETCH_EXAM_FEATURE_FAIL = 'FETCH_EXAM_FEATURE_FAIL';

export const FETCH_CATEGORIES_EXAM = 'FETCH_CATEGORIES_EXAM';
export const FETCH_CATEGORIES_EXAM_SUCCESS = 'FETCH_CATEGORIES_EXAM_SUCCESS';
export const FETCH_CATEGORIES_EXAM_FAIL = 'FETCH_CATEGORIES_EXAM_FAIL';

export const FETCH_EXAMS_BY_MULTI_CATEGORY = 'FETCH_EXAMS_BY_MULTI_CATEGORY';
export const FETCH_EXAMS_BY_MULTI_CATEGORY_SUCCESS =
  'FETCH_EXAMS_BY_MULTI_CATEGORY_SUCCESS';
export const FETCH_EXAMS_BY_MULTI_CATEGORY_FAIL =
  'FETCH_EXAMS_BY_MULTI_CATEGORY_FAIL';

export const FETCH_SECTION_BY_EXAM = 'FETCH_SECTION_BY_EXAM';
export const FETCH_SECTION_BY_EXAM_SUCCESS = 'FETCH_SECTION_BY_EXAM_SUCCESS';
export const FETCH_SECTION_BY_EXAM_FAIL = 'FETCH_SECTION_BY_EXAM_FAIL';

export const FETCH_QUESTION_BY_PART = 'FETCH_QUESTION_BY_PART';
export const FETCH_QUESTION_BY_PART_SUCCESS = 'FETCH_QUESTION_BY_PART_SUCCESS';
export const FETCH_QUESTION_BY_PART_FAIL = 'FETCH_QUESTION_BY_PART_FAIL';

export const FETCH_LIST_ESSAY_EXAM = 'FETCH_LIST_ESSAY_EXAM';
export const FETCH_LIST_ESSAY_EXAM_SUCCESS = 'FETCH_LIST_ESSAY_EXAM_SUCCESS';
export const FETCH_LIST_ESSAY_EXAM_FAIL = 'FETCH_LIST_ESSAY_EXAM_FAIL';

export const SAVE_ANSWER_ESSAY_EXAM = 'SAVE_ANSWER_ESSAY_EXAM';
export const SAVE_ANSWER_ESSAY_EXAM_SUCCESS = 'SAVE_ANSWER_ESSAY_EXAM_SUCCESS';
export const SAVE_ANSWER_ESSAY_EXAM_FAIL = 'SAVE_ANSWER_ESSAY_EXAM_FAIL';

export const GET_DETAIL_ESSAY_EXAM = 'GET_DETAIL_ESSAY_EXAM';
export const GET_DETAIL_ESSAY_EXAM_SUCCESS = 'GET_DETAIL_ESSAY_EXAM_SUCCESS';
export const GET_DETAIL_ESSAY_EXAM_FAIL = 'GET_DETAIL_ESSAY_EXAM_FAIL';

export const SET_DETAIL_ESSAY_EXAM = 'SET_DETAIL_ESSAY_EXAM';
