export const FETCH_LESSON = 'FETCH_LESSON';
export const FETCH_LESSON_FAIL = 'FETCH_LESSON_FAIL';
export const FETCH_LESSON_SUCCESS = 'FETCH_LESSON_SUCCESS';

export const FETCH_LESSON_PRACTICE_SPEAK = 'FETCH_LESSON_PRACTICE_SPEAK';
export const FETCH_LESSON_PRACTICE_SPEAK_SUCCESS =
  'FETCH_LESSON_PRACTICE_SPEAK_SUCCESS';
export const FETCH_LESSON_PRACTICE_SPEAK_FAIL =
  'FETCH_LESSON_PRACTICE_SPEAK_FAIL';

export const CHANGE_CURRENT_LESSON = 'CHANGE_CURRENT_LESSON';
export const CHANGE_CURRENT_LESSON_PRACTICE = 'CHANGE_CURRENT_LESSON_PRACTICE';

export const FETCH_TEACH_CATEGORY = 'FETCH_TEACH_CATEGORY';
export const FETCH_TEACH_CATEGORY_SUCCESS = 'FETCH_TEACH_CATEGORY_SUCCESS';
export const FETCH_TEACH_CATEGORY_FAIL = 'FETCH_TEACH_CATEGORY_FAIL';

export const FETCH_TEACH_CATEGORY_DETAIL = 'FETCH_TEACH_CATEGORY_DETAIL';
export const FETCH_TEACH_CATEGORY_DETAIL_SUCCESS =
  'FETCH_TEACH_CATEGORY_DETAIL_SUCCESS';
export const FETCH_TEACH_CATEGORY_DETAIL_FAIL =
  'FETCH_TEACH_CATEGORY_DETAIL_FAIL';
