export const FETCH_LIST_HOMEWORK = 'FETCH_LIST_HOMEWORK';
export const FETCH_LIST_HOMEWORK_SUCCESS = 'FETCH_LIST_HOMEWORK_SUCCESS';
export const FETCH_LIST_HOMEWORK_FAIL = 'FETCH_LIST_HOMEWORK_FAIL';

export const FETCH_DETAIL_HOMEWORK = 'FETCH_DETAIL_HOMEWORK';
export const FETCH_DETAIL_HOMEWORK_SUCCESS = 'FETCH_DETAIL_HOMEWORK_SUCCESS';
export const FETCH_DETAIL_HOMEWORK_FAIL = 'FETCH_DETAIL_HOMEWORK_FAIL';

export const SELECTED_HOMEWORK = 'SELECTED_HOMEWORK';
export const PUSH_PROGRESS_HOMEWORK = 'PUSH_PROGRESS_HOMEWORK';
