export const FETCH_LECTURE_LISTEN = 'FETCH_LECTURE_LISTEN';
export const FETCH_LECTURE_LISTEN_SUCCESS = 'FETCH_LECTURE_LISTEN_SUCCESS';
export const FETCH_LECTURE_LISTEN_FAIL = 'FETCH_LECTURE_LISTEN_FAIL';

export const FETCH_DEGREE_LISTEN = 'FETCH_DEGREE_LISTEN';
export const FETCH_DEGREE_LISTEN_SUCCESS = 'FETCH_DEGREE_LISTEN_SUCCESS';
export const FETCH_DEGREE_LISTEN_FAIL = 'FETCH_DEGREE_LISTEN_FAIL';
