export const FETCH_LIST_NOTIFICATION = 'FETCH_LIST_NOTIFICATION';
export const FETCH_LIST_NOTIFICATION_SUCCESS =
  'FETCH_LIST_NOTIFICATION_SUCCESS';
export const FETCH_LIST_NOTIFICATION_FAIL = 'FETCH_LIST_NOTIFICATION_FAIL';

export const MARK_READ = 'MARK_READ';
export const MARK_READ_SUCCESS = 'MARK_READ_SUCCESS';
export const MARK_READ_ALL = 'MARK_READ_ALL';
export const MARK_READ_ALL_SUCCESS = 'MARK_READ_ALL_SUCCESS';
export const INCREASE_UNREAD_NOTIFICATION = 'INCREASE_UNREAD_NOTIFICATION';
export const DECREASE_UNREAD_NOTIFICATION = 'DECREASE_UNREAD_NOTIFICATION';
