export const PUSH_ACTION = 'PUSH_ACTION';
export const PUSH_LIST_ACTIONS = 'PUSH_LIST_ACTIONS';
export const PUSH_SCRIPT_ITEM_SPEAK = 'PUSH_SCRIPT_ITEM_SPEAK';
export const RESET_ACTION = 'RESET_ACTION';
export const INCREASE_SCORE = 'INCREASE_SCORE';
export const INCREASE_WORD_SPEAK = 'INCREASE_WORD_SPEAK';
export const SET_MAX_CORRECT = 'SET_MAX_CORRECT';

export const CHANGE_CURRENT_SCRIPT_ITEM = 'CHANGE_CURRENT_SCRIPT_ITEM';

export const ANSWER_QUESTION = 'ANSWER_QUESTION';

export const DONE_ACTIVITY = 'DONE_ACTIVITY';
export const DONE_ACTIVITY_FAIL = 'DONE_ACTIVITY_FAIL';
export const DONE_ACTIVITY_SUCCESS = 'DONE_ACTIVITY_SUCCESS';
