export const CHECK_VERSION_APP = 'CHECK_VERSION_APP';
export const SET_STATUS_USER_UPDATE_APP = 'SET_STATUS_USER_UPDATE_APP';
export const UPDATE_INFO_APP = 'UPDATE_INFO_APP';
export const UPDATE_KEYBOARD_HEIGHT = 'UPDATE_KEYBOARD_HEIGHT';
export const SET_LANGUAGE_APP = 'SET_LANGUAGE_APP';
