export const LOGIN = 'LOGIN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FETCH_ME = 'FETCH_ME';
export const FETCH_ME_FAIL = 'FETCH_ME_FAIL';
export const FETCH_ME_SUCCESS = 'FETCH_ME_SUCCESS';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ADD_NOTIFICATION_TOKEN = 'ADD_NOTIFICATION_TOKEN';
export const ENABLE_NOTIFICATION = 'ENABLE_NOTIFICATION';

export const SUBSCRIBE_NOTIFICATION = 'SUBSCRIBE_NOTIFICATION';
export const UNSUBSCRIBE_NOTIFICATION = 'UNSUBSCRIBE_NOTIFICATION';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const REGISTER = 'REGISTER';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const REFRESH_USER = 'REFRESH_USER';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const SPEECH_TO_TEXT_TOKEN = 'SPEECH_TO_TEXT_TOKEN';

export const ADD_ACTION_ERROR = 'ADD_ACTION_ERROR';
export const RETRY_ACTION_ERROR = 'RETRY_ACTION_ERROR';
export const REMOVE_ACTION_ERROR = 'REMOVE_ACTION_ERROR';

export const UPDATE_FCM_TOKEN = 'UPDATE_FCM_TOKEN';
export const SAVE_FCM_TOKEN = 'SAVE_FCM_TOKEN';
export const UPDATE_TIME_USING = 'UPDATE_TIME_USING';
export const JOIN_CLASS = 'JOIN_CLASS';

export const LOGIN_GOOGLE = 'LOGIN_GOOGLE';
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS';
export const LOGIN_FB = 'LOGIN_FB';
export const LOGIN_FB_SUCCESS = 'LOGIN_FB_SUCCESS';
export const LOGIN_APPLE = 'LOGIN_APPLE';
export const LOGIN_APPLE_SUCCESS = 'LOGIN_APPLE_SUCCESS';
