export const SET_TRANSLATION = 'SET_TRANSLATION';
export const FETCH_LIST_VOCA_FEATURES = 'FETCH_LIST_VOCAL_FEATURES';
export const FETCH_LIST_VOCA_FEATURES_SUCCESS =
  'FETCH_LIST_VOCAL_FEATURES_SUCCESS';
export const FETCH_LIST_VOCA_FEATURES_FAIL = 'FETCH_LIST_VOCAL_FEATURES_FAIL';
export const FETCH_LIST_TOPIC_VOCABULARY = 'FETCH_LIST_TOPIC_VOCABULARY';
export const FETCH_LIST_TOPIC_VOCABULARY_SUCCESS =
  'FETCH_LIST_TOPIC_VOCABULARY_SUCCESS';
export const FETCH_LIST_TOPIC_VOCABULARY_FAIL =
  'FETCH_LIST_TOPIC_VOCABULARY_FAIL';
export const FETCH_TOPIC_MOST_ATTENTION = 'FETCH_TOPIC_MOST_ATTENTION';
export const FETCH_TOPIC_MOST_ATTENTION_SUCCESS =
  'FETCH_TOPIC_MOST_ATTENTION_SUCCESS';
export const FETCH_TOPIC_MOST_ATTENTION_FAIL =
  'FETCH_TOPIC_MOST_ATTENTION_FAIL';

export const FETCH_WORDS_GROUP = 'FETCH_WORDS_GROUP';
export const FETCH_WORDS_GROUP_SUCCESS = 'FETCH_WORDS_GROUP_SUCCESS';
export const FETCH_WORDS_GROUP_FAIL = 'FETCH_WORDS_GROUP_FAIL';

export const SET_IN_WORD_GROUP = 'SET_IN_WORD_GROUP';
