export const FETCH_COURSE = 'FETCH_COURSE';
export const FETCH_COURSE_FAIL = 'FETCH_COURSE_FAIL';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';

export const CHANGE_CURRENT_COURSE = 'CHANGE_CURRENT_COURSE';

export const FETCH_COMMON_COMMENT_SPEAK = 'FETCH_COMMON_COMMENT_SPEAK';
export const FETCH_COMMON_COMMENT_SPEAK_SUCCESS =
  'FETCH_COMMON_COMMENT_SPEAK_SUCCESS';
export const FETCH_COMMON_COMMENT_SPEAK_FAIL =
  'FETCH_COMMON_COMMENT_SPEAK_FAIL';
