export const FETCH_PART = 'FETCH_PART';
export const FETCH_PART_FAIL = 'FETCH_PART_FAIL';
export const FETCH_PART_SUCCESS = 'FETCH_PART_SUCCESS';

export const CHANGE_CURRENT_PART = 'CHANGE_CURRENT_PART';
export const PART_DONE = 'PART_DONE';

export const FETCH_PART_VIP = 'FETCH_PART_VIP';
export const FETCH_PART_VIP_SUCCESS = 'FETCH_PART_VIP_SUCCESS';
export const FETCH_PART_VIP_FAIL = 'FETCH_PART_VIP_FAIL';
