export const FETCH_ACTIVITY = 'FETCH_ACTIVITY';
export const FETCH_ACTIVITY_FAIL = 'FETCH_ACTIVITY_FAIL';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';

export const CHANGE_CURRENT_ACTIVITY = 'CHANGE_CURRENT_ACTIVITY';
export const RESET_ACTIVITY_DONE = 'RESET_ACTIVITY_DONE';
export const DONE_QUESTION = 'DONE_QUESTION';
export const INCREMENT_QUESTION = 'INCREMENT_QUESTION';

export const FETCH_ACTIVITY_PRACTICE_SPEAK = 'FETCH_ACTIVITY_PRACTICE_SPEAK';
export const FETCH_ACTIVITY_PRACTICE_SPEAK_SUCCESS =
  'FETCH_ACTIVITY_PRACTICE_SPEAK_SUCCESS';
export const FETCH_ACTIVITY_PRACTICE_SPEAK_FAIL =
  'FETCH_ACTIVITY_PRACTICE_SPEAK_FAIL';

export const FETCH_ACTIVITY_GRAMMAR = 'FETCH_ACTIVITY_GRAMMAR';
export const FETCH_ACTIVITY_GRAMMAR_SUCCESS = 'FETCH_ACTIVITY_GRAMMAR_SUCCESS';
export const FETCH_ACTIVITY_GRAMMAR_FAIL = 'FETCH_ACTIVITY_GRAMMAR_FAIL';

export const FETCH_ACTIVITY_COMMUNICATION = 'FETCH_ACTIVITY_COMMUNICATION';
export const FETCH_ACTIVITY_COMMUNICATION_SUCCESS =
  'FETCH_ACTIVITY_COMMUNICATION_SUCCESS';
export const FETCH_ACTIVITY_COMMUNICATION_FAIL =
  'FETCH_ACTIVITY_COMMUNICATION_FAIL';

export const FETCH_ACTIVITY_VOCABULARY = 'FETCH_ACTIVITY_VOCABULARY';
export const FETCH_ACTIVITY_VOCABULARY_SUCCESS =
  'FETCH_ACTIVITY_VOCABULARY_SUCCESS';
export const FETCH_ACTIVITY_VOCABULARY_FAIL = 'FETCH_ACTIVITY_VOCABULARY_FAIL';
export const SET_TAB_ACTIVITY = 'SET_TAB_ACTIVITY';
export const SET_SCREEN_ACTIVITY = 'SET_SCREEN_ACTIVITY';

export const FETCH_ACTIVITY_SONG = 'FETCH_ACTIVITY_SONG';
export const FETCH_ACTIVITY_SONG_SUCCESS = 'FETCH_ACTIVITY_SONG_SUCCESS';
export const FETCH_ACTIVITY_SONG_FAIL = 'FETCH_ACTIVITY_SONG_FAIL';

export const FETCH_TUTORIALS_ACTIVITY = 'FETCH_TUTORIALS_ACTIVITY';
export const FETCH_TUTORIALS_ACTIVITY_SUCCESS =
  'FETCH_TUTORIALS_ACTIVITY_SUCCESS';
export const FETCH_TUTORIALS_ACTIVITY_FAIL = 'FETCH_TUTORIALS_ACTIVITY_FAIL';
export const SET_TOTAL_QUESTION = 'SET_TOTAL_QUESTION';

export const SET_SKIP_GENERATE_ACTIVITY_AT_FIRST =
  'SET_SKIP_GENERATE_ACTIVITY_AT_FIRST';
