export const FETCH_LIST_LIVE_CLASS = 'FETCH_LIST_LIVE_CLASS';
export const FETCH_LIST_LIVE_CLASS_SUCCESS = 'FETCH_LIST_LIVE_CLASS_SUCCESS';
export const FETCH_LIST_LIVE_CLASS_FAIL = 'FETCH_LIST_LIVE_CLASS_FAIL';

export const FETCH_LIVE_CLASS_INFO = 'FETCH_LIVE_CLASS_INFO';
export const FETCH_LIVE_CLASS_INFO_SUCCESS = 'FETCH_LIVE_CLASS_INFO_SUCCESS';
export const FETCH_LIVE_CLASS_INFO_FAIL = 'FETCH_LIVE_CLASS_INFO_FAIL';

export const FETCH_SESSION_ACTIVITY = 'FETCH_SESSION_ACTIVITY';
export const FETCH_SESSION_ACTIVITY_SUCCESS = 'FETCH_SESSION_ACTIVITY_SUCCESS';
export const FETCH_SESSION_ACTIVITY_FAIL = 'FETCH_SESSION_ACTIVITY_FAIL';

export const FETCH_CLASS_LIVE_INFO = 'FETCH_CLASS_LIVE_INFO';
export const FETCH_CLASS_LIVE_INFO_SUCCESS = 'FETCH_CLASS_LIVE_INFO_SUCCESS';

export const FETCH_DOCS_LIVE = 'FETCH_DOCS_LIVE';
export const FETCH_DOCS_LIVE_SUCCESS = 'FETCH_DOCS_LIVE_SUCCESS';

export const LEAVE_LIVE_CLASS = 'LEAVE_LIVE_CLASS';
export const SET_CURRENT_WARES = 'SET_CURRENT_WARES';
export const SET_USERS_JOIN = 'SET_USERS_JOIN';
export const SET_TIMER_DOING_SCRIPT = 'SET_TIMER_DOING_SCRIPT';
export const SET_STATUS_DONE_WARES = 'SET_STATUS_DONE_WARES';
export const SET_RESULT_QUESTION_WARES = 'SET_RESULT_QUESTION_WARES';

export const UPDATE_STUDENT_SCRIPT_SCORE = 'UPDATE_STUDENT_SCRIPT_SCORE';
export const RESET_STUDENT_SCRIPT_SCORE = 'RESET_STUDENT_SCRIPT_SCORE';

export const UPDATE_SCORE_CLASS = 'UPDATE_SCORE_CLASS';
export const CREATE_DETAIL_INFO_STUDENT = 'CREATE_DETAIL_INFO_STUDENT';
export const RESET_DETAIL_RESULT_STUDENTS = 'RESET_DETAIL_RESULT_STUDENTS';
export const UPDATE_SCORE_RECONNECT = 'UPDATE_SCORE_RECONNECT';
export const SELECTED_USER_VIEW_RESULT = 'SELECTED_USER_VIEW_RESULT';

export const RESTORE_SCRIPT_STATE = 'RESTORE_SCRIPT_STATE';
export const UPDATE_STATE_JOIN_CLASS = 'UPDATE_STATE_JOIN_CLASS';

export const SET_MAIN_SCRIPT_ACTIVITY = 'SET_MAIN_SCRIPT_ACTIVITY';

export const SEND_LIVE_SCORE = 'SEND_LIVE_SCORE';

export const UPDATE_RAISE_HAND_DATA = 'UPDATE_RAISE_HAND_DATA';
export const RESTORE_RAISE_HAND_DATA = 'RESTORE_RAISE_HAND_DATA';

export const SET_SCHOOL_LIVE_CLASS_DATA = 'SET_SCHOOL_LIVE_CLASS_DATA';
export const UPDATE_COURSEWARES_DATA = 'UPDATE_COURSEWARES_DATA';
export const FETCH_MESSAGE_CLASS = 'FETCH_MESSAGE_CLASS';
export const FETCH_MESSAGE_CLASS_SUCCESS = 'FETCH_MESSAGE_CLASS_SUCCESS';
export const FETCH_MESSAGE_CLASS_FAIL = 'FETCH_MESSAGE_CLASS_FAIL';

export const FETCH_MESSAGE_PREVIEW_LINK = 'FETCH_MESSAGE_PREVIEW_LINK';
export const FETCH_MESSAGE_PREVIEW_LINK_SUCCESS =
  'FETCH_MESSAGE_PREVIEW_LINK_SUCCESS';
export const FETCH_MESSAGE_PREVIEW_LINK_FAIL =
  'FETCH_MESSAGE_PREVIEW_LINK_FAIL';

export const CLEAR_TYPING_MESSAGE = 'CLEAR_TYPING_MESSAGE';
export const RESET_CHAT_LIVE_CLASS = 'RESET_CHAT_LIVE_CLASS';

export const ADD_USER_TYPING = 'ADD_USER_TYPING';
export const REMOVE_USER_TYPING = 'REMOVE_USER_TYPING';
export const ADD_MESSAGE_ONLINE = 'ADD_MESSAGE_ONLINE';
export const SET_COLOR_CHATTING_ACCOUNT = 'SET_COLOR_CHATTING_ACCOUNT';
export const SET_COLOR_CHATTING_ACCOUNT_SUCCESS =
  'SET_COLOR_CHATTING_ACCOUNT_SUCCESS';
export const SET_HAS_NEW_MESSAGE = 'SET_HAS_NEW_MESSAGE';

export const RECEIVE_UPDATE_SCORE_EVENT = 'RECEIVE_UPDATE_SCORE_EVENT';
export const UPDATE_SCORE_WHEN_DONE_WARES = 'UPDATE_SCORE_WHEN_DONE_WARES';

export const COURSEWARE_OPEN_ACTION = 'COURSEWARE_OPEN_ACTION';

export const COURSEWARE_ACTION_SOCKET = 'COURSEWARE_ACTION_SOCKET';

export const COUNTDOWN_START_ACTION = 'COUNTDOWN_START_ACTION';

export const COUNTDOWN_REMOVE_ACTION = 'COUNTDOWN_REMOVE_ACTION';

export const NEW_USER_JOIN_ZOOM = 'NEW_USER_JOIN_ZOOM';

export const ADD_NEW_USER_JOIN_ZOOM_SUCCESS = 'ADD_NEW_USER_JOIN_ZOOM_SUCCESS';

export const UPDATE_STATUS_MEMBER = 'UPDATE_STATUS_MEMBER';

export const LEAVE_USER_ZOOM = 'LEAVE_USER_ZOOM';

export const SET_CURRENT_LESSON = 'SET_CURRENT_LESSON';

export const SET_SHOW_VIDEO_ZOOM = 'SET_SHOW_VIDEO_ZOOM';

export const RESTORE_REACTIVE_COURSEWARE_DATA =
  'RESTORE_REACTIVE_COURSEWARE_DATA';

export const RECEIVE_REACTIVE_COURSEWARE_ACTION =
  'RECEIVE_REACTIVE_COURSEWARE_ACTION';

export const UPDATE_REACTIVE_COURSEWARE_DATA =
  'UPDATE_REACTIVE_COURSEWARE_DATA';

export const REMOVE_REACTIVE_COURSEWARE = 'REMOVE_REACTIVE_COURSEWARE';

export const SET_SHOW_LATENCY_CONTAINER = 'SET_SHOW_LATENCY_CONTAINER';
export const SET_LATENCY_CLIENT_SERVER = 'SET_LATENCY_CLIENT_SERVER';

export const UPDATE_AUDIO_STATUS_ZOOM = 'UPDATE_AUDIO_STATUS_ZOOM';
export const UPDATE_VIDEO_STATUS_ZOOM = 'UPDATE_VIDEO_STATUS_ZOOM';

export const LOAD_AUDIO_REACTIVE_STATUS = 'LOAD_AUDIO_REACTIVE_STATUS';
export const LOAD_VIDEO_REACTIVE_STATUS = 'LOAD_VIDEO_REACTIVE_STATUS';
