export const FETCH_DETAIL_CLASS = 'FETCH_DETAIL_CLASS';
export const FETCH_DETAIL_CLASS_SUCCESS = 'FETCH_DETAIL_CLASS_SUCCESS';
export const FETCH_DETAIL_CLASS_FAIL = 'FETCH_DETAIL_CLASS_FAIL';

export const SET_QUERY_SELECTED = 'SET_QUERY_SELECTED';
